import DataLinehhhjj88service_characteristic_logEController from '../data-line-hhhjj88-service-characteristic-log-e';

var DataLinehhhjj88service_characteristic_logENewController = DataLinehhhjj88service_characteristic_logEController;
export default DataLinehhhjj88service_characteristic_logENewController;
