import DataLinehhhjj88service_spec_characteristicEController from '../data-line-hhhjj88-service-spec-characteristic-e';

var DataLinehhhjj88service_spec_characteristicENewController = DataLinehhhjj88service_spec_characteristicEController;
export default DataLinehhhjj88service_spec_characteristicENewController;
